// Auto-generated by generate-gallery-metadata.ts. Do not edit manually.
import type { GalleryImage } from './gallery-images';

export const GENERATED_GALLERY_IMAGES: readonly GalleryImage[] = [
  {
    id: 1,
    path: 'Dogs/DSC_0107',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 1467,
    order: 1,
  },
  {
    id: 2,
    path: 'Dogs/DSC_0187',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 1467,
  },
  {
    id: 3,
    path: 'Dogs/DSC_0528',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 4,
    path: 'Dogs/DSC_0901',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 5,
    path: 'Dogs/DSC_0909',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 1467,
  },
  {
    id: 6,
    path: 'Dogs/DSC_1195',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
    order: 2,
  },
  {
    id: 7,
    path: 'Dogs/DSC_3299',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 1467,
  },
  {
    id: 8,
    path: 'Dogs/DSC_3315',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 9,
    path: 'Dogs/DSC_6319.sv',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3093,
  },
  {
    id: 10,
    path: 'Dogs/DSC_6367',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3093,
  },
  {
    id: 11,
    path: 'Dogs/DSC_6447',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 1467,
    order: 3,
  },
  {
    id: 12,
    path: 'Dogs/DSC_6972',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3093,
  },
  {
    id: 13,
    path: 'Dogs/DSC_7640',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 14,
    path: 'Dogs/DSC_8189',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 15,
    path: 'Dogs/DSC_9156',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 1467,
  },
  {
    id: 16,
    path: 'Dogs/DSC_9573',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 17,
    path: 'Dogs/IMG_0129.extra',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 18,
    path: 'Dogs/IMG_0367',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 1181,
    height: 1772,
  },
  {
    id: 19,
    path: 'Dogs/IMG_0615',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 1467,
  },
  {
    id: 20,
    path: 'Dogs/IMG_3344',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 21,
    path: 'Dogs/IMG_3725',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 22,
    path: 'Dogs/IMG_4629',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 23,
    path: 'Dogs/IMG_5351sv',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 1772,
    height: 1181,
  },
  {
    id: 24,
    path: 'Dogs/IMG_5553sv',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 1181,
    height: 1772,
  },
  {
    id: 25,
    path: 'Dogs/IMG_5811',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 1181,
    height: 1772,
  },
  {
    id: 26,
    path: 'Dogs/IMG_5866',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 27,
    path: 'Dogs/IMG_7050sv',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 1181,
    height: 1772,
  },
  {
    id: 28,
    path: 'Dogs/IMG_8277',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 1181,
    height: 1772,
  },
  {
    id: 29,
    path: 'Dogs/IMG_8315',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 2200,
    height: 3300,
  },
  {
    id: 30,
    path: 'Dogs/IMG_8888',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 1772,
    height: 1181,
  },
  {
    id: 31,
    path: 'Dogs/IMG_9954',
    altKey: '', // TODO: fill i18n key
    tags: ['dogs'],
    width: 1772,
    height: 1181,
  },
  {
    id: 32,
    path: 'Cats/DSC_3150',
    altKey: '', // TODO: fill i18n key
    tags: ['cats'],
    width: 2200,
    height: 3300,
    order: 4,
  },
  {
    id: 33,
    path: 'Cats/DSC_3193',
    altKey: '', // TODO: fill i18n key
    tags: ['cats'],
    width: 2200,
    height: 3300,
  },
  {
    id: 34,
    path: 'Cats/DSC_3369',
    altKey: '', // TODO: fill i18n key
    tags: ['cats'],
    width: 2200,
    height: 3300,
  },
  {
    id: 35,
    path: 'Cats/IMG_7486',
    altKey: '', // TODO: fill i18n key
    tags: ['cats'],
    width: 1181,
    height: 1772,
    order: 5,
  },
  {
    id: 36,
    path: 'Cats/IMG_7545',
    altKey: '', // TODO: fill i18n key
    tags: ['cats'],
    width: 1181,
    height: 1772,
  },
  {
    id: 37,
    path: 'Farm Animals/IMG_6840',
    altKey: '', // TODO: fill i18n key
    tags: ['farm animals'],
    width: 1772,
    height: 1181,
    order: 6,
  },
  {
    id: 38,
    path: 'Farm Animals/IMG_6928',
    altKey: '', // TODO: fill i18n key
    tags: ['farm animals'],
    width: 1181,
    height: 1772,
  },
  {
    id: 39,
    path: 'Farm Animals/IMG_7038',
    altKey: '', // TODO: fill i18n key
    tags: ['farm animals'],
    width: 1181,
    height: 1772,
  },
  {
    id: 40,
    path: 'Farm Animals/IMG_7043',
    altKey: '', // TODO: fill i18n key
    tags: ['farm animals'],
    width: 1181,
    height: 1772,
  },
  {
    id: 41,
    path: 'Farm Animals/IMG_7079',
    altKey: '', // TODO: fill i18n key
    tags: ['farm animals'],
    width: 1181,
    height: 1772,
    order: 7,
  },
  {
    id: 42,
    path: 'Farm Animals/IMG_7087',
    altKey: '', // TODO: fill i18n key
    tags: ['farm animals'],
    width: 1181,
    height: 1772,
  },
  {
    id: 43,
    path: 'Farm Animals/IMG_7098',
    altKey: '', // TODO: fill i18n key
    tags: ['farm animals'],
    width: 1181,
    height: 1772,
  },
  {
    id: 44,
    path: 'Farm Animals/IMG_7135',
    altKey: '', // TODO: fill i18n key
    tags: ['farm animals'],
    width: 1181,
    height: 1772,
  },
  {
    id: 45,
    path: 'Farm Animals/IMG_7202',
    altKey: '', // TODO: fill i18n key
    tags: ['farm animals'],
    width: 1181,
    height: 1772,
  },
  {
    id: 46,
    path: 'Portraits/DSC_4716',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 3093,
  },
  {
    id: 47,
    path: 'Portraits/DSC_4751',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 3093,
  },
  {
    id: 48,
    path: 'Portraits/DSC_8059',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 3300,
  },
  {
    id: 49,
    path: 'Portraits/DSC_8351',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 1467,
  },
  {
    id: 50,
    path: 'Portraits/DSC_8625',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 3300,
  },
  {
    id: 51,
    path: 'Portraits/DSC_8672',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 1467,
  },
  {
    id: 52,
    path: 'Portraits/DSC_8822sv',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 1467,
  },
  {
    id: 53,
    path: 'Portraits/DSC_8872',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 1467,
  },
  {
    id: 54,
    path: 'Portraits/IMG_1746',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 3300,
  },
  {
    id: 55,
    path: 'Portraits/IMG_1890',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 3300,
  },
  {
    id: 56,
    path: 'Portraits/IMG_1958',
    altKey: '', // TODO: fill i18n key
    tags: ['portraits'],
    width: 2200,
    height: 3300,
  },
  {
    id: 57,
    path: 'Details/DSC_6633',
    altKey: '', // TODO: fill i18n key
    tags: ['details'],
    width: 2200,
    height: 1467,
  },
  {
    id: 58,
    path: 'Details/DSC_6838',
    altKey: '', // TODO: fill i18n key
    tags: ['details'],
    width: 2200,
    height: 1467,
  },
  {
    id: 59,
    path: 'Details/DSC_6939',
    altKey: '', // TODO: fill i18n key
    tags: ['details'],
    width: 2200,
    height: 1467,
  },
] as const;
