import fs from 'fs';
import path from 'path';
import sharp, { Metadata } from 'sharp';
import { IMAGE_INPUT_ROOT, IMAGE_OUTPUT_ROOT, METADATA_INPUT_FILE, METADATA_OUTPUT_FILE } from '../config';
import { ImageMetadata, parseCsv, readRawCsv } from './parse-csv';
import { GALLERY_WIDTHS } from '../../../app/pages/gallery/images/gallery-images';

function getFolderNames(): string[] {
  return fs
    .readdirSync(IMAGE_INPUT_ROOT, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);
}

function buildImageKey(image: ImageMetadata): string {
  return `${image.folder}/${image.name}`;
}

async function getAvifImageMetadata(image: ImageMetadata): Promise<Metadata> {
  const largestWidth = GALLERY_WIDTHS[GALLERY_WIDTHS.length - 1];
  const avifPath = path.join(IMAGE_OUTPUT_ROOT, image.folder, `${image.name}-${largestWidth}.avif`);

  try {
    return await sharp(avifPath).metadata();
  } catch (err) {
    throw new Error('Failed to read avif image data for image: ' + path.join(image.folder, image.name), {
      cause: err,
    });
  }
}

async function writeTsFile(images: ImageMetadata[]): Promise<void> {
  const lines: string[] = [];

  lines.push('// Auto-generated by generate-gallery-metadata.ts. Do not edit manually.');
  lines.push("import type { GalleryImage } from './gallery-images';");
  lines.push('');
  lines.push('export const GENERATED_GALLERY_IMAGES: readonly GalleryImage[] = [');

  let id = 1;
  for (const img of images) {
    const pathKey = buildImageKey(img);
    const tagsArray = img.tags.map((t) => `'${t}'`).join(', ');

    const meta = await getAvifImageMetadata(img);

    lines.push('  {');
    lines.push(`    id: ${id},`);
    lines.push(`    path: '${pathKey}',`);
    lines.push(`    tags: [${tagsArray}],`);
    lines.push(`    width: ${meta.width},`);
    lines.push(`    height: ${meta.height},`);
    if (img.order !== undefined) {
      lines.push(`    order: ${img.order},`);
    }
    lines.push('  },');

    id += 1;
  }

  lines.push('] as const;');
  lines.push('');

  fs.mkdirSync(path.dirname(METADATA_OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(METADATA_OUTPUT_FILE, lines.join('\n'), 'utf8');

  console.log(`Wrote metadata to ${METADATA_OUTPUT_FILE}`);
}

function updateI18nFiles(images: ImageMetadata[]): void {
  const languages: {
    lang: 'en' | 'sv';
    file: string;
    pick: (img: ImageMetadata) => string | undefined;
  }[] = [
    {
      lang: 'en',
      file: path.resolve(__dirname, '../../../app/pages/gallery/i18n/en-image-descriptions.json'),
      pick: (img) => img.englishDescription,
    },
    {
      lang: 'sv',
      file: path.resolve(__dirname, '../../../app/pages/gallery/i18n/sv-image-descriptions.json'),
      pick: (img) => img.swedishDescription,
    },
  ];

  for (const { lang, file, pick } of languages) {
    const imagesNode: Record<string, { alt: string }> = {};

    const missing: string[] = [];

    for (const img of images) {
      const imageKey = buildImageKey(img);
      const descRaw = pick(img);
      const desc = descRaw?.trim();

      if (!desc) {
        missing.push(imageKey);
        continue;
      }

      imagesNode[imageKey] = { alt: desc };
    }

    if (missing.length > 0) {
      console.warn(`[i18n] Missing descriptions for ${missing.length} images in ${lang}: ${missing.join(', ')}`);
    }

    const root = {
      galleryDescriptions: {
        images: imagesNode,
      },
    };

    const pretty = JSON.stringify(root, null, 2);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, pretty + '\n', 'utf8');
    console.log(`Updated gallery image-descriptions i18n file: ${file}`);
  }
}

async function main(): Promise<void> {
  const folders = getFolderNames();
  const rawCsv = readRawCsv(METADATA_INPUT_FILE);
  const imageMetadata = parseCsv(new Set(folders), rawCsv);

  console.log(`Generating metadata for ${imageMetadata.length} images...`);
  await writeTsFile(imageMetadata);
  updateI18nFiles(imageMetadata);
}

void main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
