import fs from 'fs';
import path from 'path';
import sharp, { Metadata } from 'sharp';
import {
  IMAGE_INPUT_ROOT,
  IMAGE_OUTPUT_ROOT,
  LARGEST_GALLERY_WIDTH,
  METADATA_INPUT_FILE,
  METADATA_OUTPUT_FILE,
} from '../config';
import { ImageMetadata, parseCsv, readRawCsv } from './parse-csv';

function getFolderNames(): string[] {
  return fs
    .readdirSync(IMAGE_INPUT_ROOT, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);
}

async function getAvifImageMetadata(image: ImageMetadata): Promise<Metadata> {
  const avifPath = path.join(IMAGE_OUTPUT_ROOT, image.folder, `${image.name}-${LARGEST_GALLERY_WIDTH}.avif`);

  try {
    return await sharp(avifPath).metadata();
  } catch (err) {
    throw new Error('Failed to read avif image data for image: ' + path.join(image.folder, image.name), {
      cause: err,
    });
  }
}

async function writeTsFile(images: ImageMetadata[]): Promise<void> {
  const lines: string[] = [];

  lines.push('// Auto-generated by generate-gallery-metadata.ts. Do not edit manually.');
  lines.push("import type { GalleryImage } from './gallery-images';");
  lines.push('');
  lines.push('export const GENERATED_GALLERY_IMAGES: readonly GalleryImage[] = [');

  let id = 1;
  for (const img of images) {
    const pathKey = `${img.folder}/${img.name}`;
    const tagsArray = img.tags.map((t) => `'${t}'`).join(', ');
    const orderField = img.order !== undefined ? `, order: ${img.order}` : '';

    const meta = await getAvifImageMetadata(img);

    lines.push('  {');
    lines.push(`    id: ${id},`);
    lines.push(`    path: '${pathKey}',`);
    lines.push("    altKey: '', // TODO: fill i18n key");
    lines.push(`    tags: [${tagsArray}]${orderField},`);
    lines.push(`    width: ${meta.width},`);
    lines.push(`    height: ${meta.height},`);
    lines.push('  },');

    id += 1;
  }

  lines.push('] as const;');
  lines.push('');

  fs.mkdirSync(path.dirname(METADATA_OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(METADATA_OUTPUT_FILE, lines.join('\n'), 'utf8');

  console.log(`Wrote metadata to ${METADATA_OUTPUT_FILE}`);
}

async function main(): Promise<void> {
  const folders = getFolderNames();

  const rawCsv = readRawCsv(METADATA_INPUT_FILE);
  const imageMetadata = parseCsv(new Set(folders), rawCsv);

  console.log(`Generating metadata for ${imageMetadata.length} images...`);
  await writeTsFile(imageMetadata);
}

void main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
